### ISSUE TITLE
parseFrom(NULL) error

### ISSUE THREAD

**Issue by plash29** [2amigos/yii2-twilio-component#2]
<pre>Exception &#039;TypeError&#039; with message &#039;Argument 1 passed to dosamigos\twilio\TwilioComponent::parseFrom() must be of the type string, null given, called in E:\wamp64\www\GigsHero\vendor\2amigos\yii2-twilio-component\src\TwilioComponent.php on line 69&#039; 

in E:\wamp64\www\GigsHero\vendor\2amigos\yii2-twilio-component\src\TwilioComponent.php:114

Stack trace:
#0 E:\wamp64\www\GigsHero\vendor\2amigos\yii2-twilio-component\src\TwilioComponent.php(69): dosamigos\twilio\TwilioComponent-&gt;parseFrom(NULL)
#1 E:\wamp64\www\GigsHero\controllers\RegistrationController.php(108): dosamigos\twilio\TwilioComponent-&gt;sms(&#039;9501045616&#039;, &#039;Hello World!&#039;)
#2 [internal function]: app\controllers\RegistrationController-&gt;actionCustomer()
#3 E:\wamp64\www\GigsHero\vendor\yiisoft\yii2\base\InlineAction.php(57): call_user_func_array(Array, Array)
#4 E:\wamp64\www\GigsHero\vendor\yiisoft\yii2\base\Controller.php(157): yii\base\InlineAction-&gt;runWithParams(Array)
#5 E:\wamp64\www\GigsHero\vendor\yiisoft\yii2\base\Module.php(528): yii\base\Controller-&gt;runAction(&#039;customer&#039;, Array)
#6 E:\wamp64\www\GigsHero\vendor\yiisoft\yii2\web\Application.php(103): yii\base\Module-&gt;runAction(&#039;registration/cu...&#039;, Array)
#7 E:\wamp64\www\GigsHero\vendor\yiisoft\yii2\base\Application.php(386): yii\web\Application-&gt;handleRequest(Object(yii\web\Request))
#8 E:\wamp64\www\GigsHero\web\index.php(17): yii\base\Application-&gt;run()
#9 {main}</pre>

**Comment by stevekr** [comment]
Getting the same error

**Comment by Aksi0** [comment]
Getting the same

**Comment by kublermdk** [comment]
Any resolution on this? I'm also having the same issue.

```
'twilio' => [
    'class' => '\dosamigos\twilio\TwilioComponent', // Based off https://github.com/2amigos/yii2-twilio-component
    'sid' => 'ACd34ca65b....', 
    'token' => '895709be8...',
    'phoneNumber' => '+15005550006' // Test phone number https://www.twilio.com/docs/iam/test-credentials
]
```

It looks like the phoneNumber isn't being picked up. But I've tried different numbers, including the example test ones that should always be valid and it's not working. The error occurs when running the  the `Yii::$app->twilio->sms($user->mobile, $messageContents);` method.

Looks like it could be because I'm not specifying the from in the call?

If I do, then it works. e.g

`Yii::$app->twilio->sms($user->mobile, $messageContents, ['from' => '+15005550006']);`

Simply removing the `string` qualifier from vendor/2amigos/yii2-twilio-component/src/TwilioComponent.php:114 also fixes the issue.
e.g:
`protected function parseFrom($from): string`

As it looks like null should be allowed as well as a string.

**Comment by Eseperio** [comment]
Since PHP 7.1 you can set the property optional prepending a question sign
```
    protected function parseFrom(?string $from): string

```

https://wiki.php.net/rfc/nullable-casting
